[package]
name = "zero_passcli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero_pass_backend = "0.0.4"
clipboard = "0.5.0"
toml = "0.5.8"
tui = "0.15.0"
home = "0.5.3"
