[package]
name = "zero_pass-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero_pass_backend = "0.0.6"
toml = "0.5.8"
home = "0.5.3"
